name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Generate Signing Key
      run: |
        keytool -genkey -v -keystore /home/runner/work/WristAssist/WristAssist/app/my-release-key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias my-key-alias -storepass mypassword -keypass mypassword -dname "CN=My Company, OU=My Org Unit, O=My Organization, L=My City, ST=My State, C=My Country"
      
    - name: Sign APK
      run: |
        wget https://dl.google.com/android/repository/build-tools_r29.0.2-linux.zip -O /tmp/build-tools.zip
        unzip /tmp/build-tools.zip -d /tmp/build-tools/
        /tmp/build-tools/build-tools/29.0.2/apksigner sign --ks /home/runner/work/WristAssist/WristAssist/app/my-release-key.jks --ks-key-alias my-key-alias --ks-pass pass:mypassword --key-pass pass:mypassword --out /home/runner/work/WristAssist/WristAssist/app/build/outputs/apk/release/app-release-signed.apk /home/runner/work/WristAssist/WristAssist/app/build/outputs/apk/release/app-release-unsigned.apk
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: apk
        path: /home/runner/work/WristAssist/WristAssist/app/build/outputs/apk/release/app-release-signed.apk
