name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
    - name: Sign apk with Random Key
      run: wget https://github.com/patrickfav/uber-apk-signer/releases/download/v1.3.0/uber-apk-signer-1.3.0.jar -O /tmp/ub.jar && java -jar /tmp/ub.jar --apks /home/runner/work/WristAssist/WristAssist/app/build/outputs/apk/release -o /home/runner/work/WristAssist/WristAssist/app/build/outputs/apk/release      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: apk
        path: /home/runner/work/WristAssist/WristAssist/app/build/outputs/apk
